import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const servicesList = [
  {
    title: "Desentupidora Comercial",
    url: "/desentupimentos/desentupimento-comercial",
  },
  {
    title: "Desentupidora Residencial",
    url: "/desentupimentos/desentupimento-residencial",
  },
  // {
  //   title: "Desentupidora Emergencial",
  //   url: "/desentupimentos/desentupimento-emergencial",
  // },
  {
    title: "Desentupidora de sumidouro",
    url: "/desentupimentos/limpeza-de-sumidouro-rj",
  },
  {
    title: "Limpeza de Fossa",
    url: "/desentupimentos/limpeza-de-fossa",
  },
  {
    title: "Desentupidora de Caixa Esgoto",
    url: "/desentupimentos/desentupimento-de-esgoto",
  },
  {
    title: "Desentupidora de Pia",
    url: "/desentupimentos/desentupimento-de-pia",
  },
  {
    title: "Desentupidora de Vaso Sanitário",
    url: "/desentupimentos/desentupimento-de-vaso-sanitario",
  },
  {
    title: "Desentupidora de Ralo Entupido",
    url: "/desentupimentos/desentupimento-de-ralo-entupido",
  },
  {
    title: "Desentupidora de Caixa de Gordura",
    url: "/desentupimentos/desentupimento-de-caixa-de-gordura",
  },
  {
    title: "Desentupidora de Coluna de Prédio",
    url: "/desentupimentos/desentupimento-de-coluna",
  },
  {
    title: "Desentupidora de Água potável",
    url: "/desentupimentos/desentupimento-de-agua-potavel",
  },
];

type Area = {
  zone: string;
  link: string;
  neighborhoods: string[];
};
export const areasDeAtendimento: Area[] = [
  {
    zone: "Zona Sul",
    link: "/rj/desentupidora-zona-sul-rj",
    neighborhoods: [
      "Botafogo",
      "Catete",
      "Copacabana",
      "Cosme Velho",
      "Flamengo",
      "Gávea",
      "Glória",
      "Humaitá",
      "Ipanema",
      "Jardim Botânico",
      "Lagoa",
      "Laranjeiras",
      "Leblon",
      "Leme",
      "São Conrado",
      "Urca",
    ],
  },
  {
    zone: "Zona Oeste",
    link: "/rj/desentupidora-zona-oeste-rj",
    neighborhoods: [
      "Bangu",
      "Barra da Tijuca",
      "Campo Grande",
      "Cosmos",
      "Curicica",
      "Deodoro",
      "Gardênia Azul",
      "Grumari",
      "Inhoaíba",
      "Itanhangá",
      "Jabour",
      "Jacarepaguá",
      "Jardim Sulacap",
      "Joá",
      "Magalhães Bastos",
      "Paciência",
      "Padre Miguel",
      "Praça Seca",
      "Pechincha",
      "Pedra de Guaratiba",
      "Realengo",
      "Rio das Pedras",
      "Recreio dos Bandeirantes",
      "Santa Cruz",
      "Santíssimo",
      "Senador Camará",
      "Senador Vasconcelos",
      "Taquara",
      "Vargem Grande",
      "Vargem Pequena",
      "Vila Kennedy",
      "Vila Militar",
      "Vila Valqueire",
    ],
  },
  {
    zone: "Centro",
    link: "/rj/desentupidora-centro-rj",
    neighborhoods: [
      "São Cristóvão",
      "Benfica",
      "Catumbi",
      "Centro",
      "Cidade Nova",
      "Estácio",
      "Lapa",
      "Rio Comprido",
      "Santa Teresa",
    ],
  },
  {
    zone: "Zona Norte",
    link: "/rj/desentupidora-zona-norte-rj",
    neighborhoods: [
      "Acari",
      "Alto da Boa Vista",
      "Anchieta",
      "Andaraí",
      "Bonsucesso",
      "Cascadura",
      "Cidade Universitária",
      "Cocotá",
      "Coelho Neto",
      "Colégio",
      "Complexo do Alemão",
      "Cordovil",
      "Costa Barros",
      "Del Castilho",
      "Encantado",
      "Engenheiro Leal",
      "Engenho da Rainha",
      "Engenho de Dentro",
      "Engenho Novo",
      "Freguesia",
      "Galeão",
      "Grajaú",
      "Guadalupe",
      "Higienópolis",
      "Honório Gurgel",
      "Inhaúma",
      "Irajá",
      "Jardim América",
      "Jardim Carioca",
      "Madureira",
      "Maracanã",
      "Marechal Hermes",
      "Maria da Graça",
      "Méier",
      "Olaria",
      "Oswaldo Cruz",
      "Parque Colúmbia",
      "Pavuna",
      "Penha",
      "Piedade",
      "Pilares",
      "Pitangueiras",
      "Praça da Bandeira",
      "Quintino Bocaiúva",
      "Ramos",
      "Riachuelo",
      "Rocha Miranda",
      "Sampaio",
      "São Francisco Xavier",
      "Tijuca",
      "Todos os Santos",
      "Tomás Coelho",
      "Vaz Lobo",
      "Vicente de Carvalho",
      "Vila Isabel Abolição",
      "Vista Alegre",
    ],
  },
];

export const urlBase = "https://desentupidorarenovo.com.br";
